// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1649699797);
user_pref("app.update.lastUpdateTime.region-update-timer", 1649700037);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1649699557);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1649699677);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1649699587);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1649699917);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.region.update.updated", 1649699531);
user_pref("browser.search.region", "DE");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Europe/Uzhgorod");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1649699539932");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1649699797);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220305171341");
user_pref("extensions.lastAppVersion", "91.7.0");
user_pref("extensions.lastPlatformVersion", "91.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"1b538e5c-84d1-468e-be50-508c1579ec1b\",\"google@search.mozilla.org\":\"68e57b8e-6980-49da-ba3a-9056309fe63d\",\"ddg@search.mozilla.org\":\"dfed5a17-ce31-4c95-a7d5-85c39eb7f7a0\",\"amazondotcom@search.mozilla.org\":\"462eb4ff-11dc-45b2-a573-2e4a97ab218b\",\"wikipedia@search.mozilla.org\":\"fe517677-3373-4585-966f-fee2af32f36d\",\"bing@search.mozilla.org\":\"86146b25-5981-4fb2-9097-12027531812d\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1649699734);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "be83b5fc-1593-4a64-a4ca-047575e8d44");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.7.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1649699734);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("security.sandbox.plugin.tempDirSuffix", "91c66d21-7a20-45a5-ac48-67adb27af2da");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1649699734);
user_pref("toolkit.telemetry.cachedClientID", "5afe6b78-587a-4e57-90ab-4ffaefb99826");
user_pref("toolkit.telemetry.previousBuildID", "20220305171341");
